# Generated by Django 2.0.8 on 2018-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='default',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
    ]
