# Generated by Django 2.0.8 on 2018-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_extended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='The plan was extended until this date'),
        ),
    ]
